// The react-pdf document for a cotización PDF (PDF-02/PDF-03/D-06/D-08). This module is PURE
// layout: it takes an already-formatted PdfModel + a header + a QR data-URL and returns a react-pdf
// Document element. It performs NO I/O — no ./env, no store, no queue — so the render test needs zero
// infra and the phase's highest-risk piece (font resolution in Alpine) is proven before any consumer
// wiring exists.
//
// Authored with React.createElement (aliased `h`), NOT JSX / .tsx: the worker's tsup build has no JSX
// transform (RESEARCH Pitfall 4). The worker never re-formats numbers (T-04-06) — every string here
// arrives pre-formatted es-AR from @imbau/quoting's toPdfModel.

import { createElement as h } from "react";
import {
  Document,
  Page,
  View,
  Text,
  Image,
  Font,
  StyleSheet,
} from "@react-pdf/renderer";
import { fileURLToPath } from "node:url";
import type { PdfModel } from "@imbau/quoting";

// Register the embedded font ONCE at module top-level (never per call) by ABSOLUTE path
// (RESEARCH Pitfall 1/2). `new URL("../assets/…", import.meta.url)` resolves to apps/worker/assets in
// BOTH the src tree (vitest: apps/worker/src/../assets) and the bundled dist (apps/worker/dist/../assets)
// — the Dockerfile COPY puts the TTF at /app/apps/worker/assets so it resolves at runtime too. A local
// filesystem path loads synchronously; a remote URL or a relative path is the #1 way accents break in
// the Chromium-free Alpine worker (PDF-02).
Font.register({
  family: "Doc",
  fonts: [
    {
      src: fileURLToPath(new URL("../assets/doc-sans-regular.ttf", import.meta.url)),
    },
    {
      src: fileURLToPath(new URL("../assets/doc-sans-bold.ttf", import.meta.url)),
      fontWeight: "bold",
    },
  ],
});

/**
 * The header block of the cotización PDF. ALL fields are strings — the worker never re-formats numbers
 * (T-04-06); the caller (plan 02 processor) builds these from the quote row + WEB_PUBLIC_BASE_URL.
 */
export type QuoteHeader = {
  proyecto: string;
  unidad: string;
  piso: string;
  tipologia: string;
  m2: string;
  fecha: string;
  cacPeriodo: string;
  ref: string;
  deepLink: string;
};

/**
 * The full input to `QuoteDoc`: the pure `PdfModel` (lineas + leyendas) from @imbau/quoting, the header,
 * and the QR as a PNG data-URL (generated by the wave-2 processor from `deepLink`). No I/O types here.
 */
export type QuoteDocProps = {
  model: PdfModel;
  header: QuoteHeader;
  qrPng: string;
};

// Neutral / minimalist styling (D-06): dark-neutral text on white — no dark backgrounds, no cobre
// brand accent. Embedded fontFamily "Doc" so es-AR glyphs render from the committed TTF.
const s = StyleSheet.create({
  page: { padding: 48, fontFamily: "Doc", fontSize: 11, color: "#1a1a1a" },
  h1: { fontSize: 16, fontWeight: "bold", marginBottom: 8 },
  meta: { fontSize: 10, color: "#555", marginBottom: 2 },
  subtitle: { fontSize: 11, marginBottom: 2 },
  linesBlock: { marginTop: 16 },
  row: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginVertical: 3,
  },
  rowLabel: { color: "#333" },
  rowValor: { fontWeight: "bold" },
  legalBlock: { marginTop: 16 },
  legal: { fontSize: 8, color: "#555", marginTop: 4 },
  footer: {
    position: "absolute",
    bottom: 32,
    left: 48,
    right: 48,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-end",
  },
  deepLink: { fontSize: 9, color: "#555", flex: 1, marginRight: 12 },
  qr: { width: 64, height: 64 },
});

/**
 * Build the cotización PDF document from a `PdfModel` + header + QR data-URL. Returns a react-pdf
 * Document element (render it with `renderToBuffer` in the wave-2 processor). One A4 page, top→bottom:
 * header block → model.lineas rows → leyendas → footer (deep-link + QR). Pure — no I/O.
 */
export function QuoteDoc({ model, header, qrPng }: QuoteDocProps) {
  return h(
    Document,
    {},
    h(
      Page,
      { size: "A4", style: s.page },
      // Header block
      h(Text, { style: s.h1 }, header.proyecto),
      h(
        Text,
        { style: s.subtitle },
        `${header.unidad} · Piso ${header.piso} · ${header.tipologia} · ${header.m2} m²`,
      ),
      h(
        Text,
        { style: s.meta },
        `Emitida: ${header.fecha} · CAC: ${header.cacPeriodo} · Ref: ${header.ref}`,
      ),
      // The quote lines (label left / valor right)
      h(
        View,
        { style: s.linesBlock },
        ...model.lineas.map((l, i) =>
          h(
            View,
            { key: `linea-${i}`, style: s.row },
            h(Text, { style: s.rowLabel }, l.label),
            h(Text, { style: s.rowValor }, l.valor),
          ),
        ),
      ),
      // Legal leyendas (PDF-03) — both strings from PdfModel.leyendas
      h(
        View,
        { style: s.legalBlock },
        ...model.leyendas.map((t, i) =>
          h(Text, { key: `leyenda-${i}`, style: s.legal }, t),
        ),
      ),
      // Footer: deep-link (left) + QR (right) — the cotizador deep-link (D-08)
      h(
        View,
        { style: s.footer },
        h(Text, { style: s.deepLink }, header.deepLink),
        h(Image, { src: qrPng, style: s.qr }),
      ),
    ),
  );
}
