// quotes — quoting table (SCHEMA-03). Clones ONLY the TENANT portion of projects.ts:
// quotes is TENANT-PRIVATE (resolved decision A5) — NO anon policy, NO anon GRANT — so an anon
// SELECT raises 42501 (asserted in 01-06). The Fase-3 cotizador consumes this contract; this
// plan ships the table, NOT the calc engine.
//
// snapshot is the versioned envelope (D-13): jsonb().$type<QuoteSnapshot>(). The envelope is
// fixed (`{ version: 1 }`) while the calc interior stays open and owned by packages/quoting; the
// co-located `quoteInsertSchema` validates it via the hand-authored quoteSnapshotSchema.
//
// lead_id is a NULLABLE pointer with NO Drizzle `.references()` and NO import of ./leads: the
// single-column FK to leads is added in plan 01-04 hand SQL to keep the module graph acyclic
// (leads also references quotes — the cycle is broken at the module layer, D / cycle-break note).
import { pgTable, uuid, text, jsonb, pgPolicy, foreignKey, unique } from "drizzle-orm/pg-core";
import { sql } from "drizzle-orm";
import { createInsertSchema } from "drizzle-zod";
import { organization } from "./auth-schema";
import { projects } from "./projects";
import { units } from "./units";
import { paymentPlans } from "./payment-plans";
import { appAuthenticated } from "./roles";
import { quoteSnapshotSchema, type QuoteSnapshot } from "./json-schemas";

export const quotes = pgTable(
  "quotes",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    // Denormalized tenant key (D-01). TEXT to match organization.id (Pitfall 2).
    organizationId: text("organization_id")
      .notNull()
      .references(() => organization.id, { onDelete: "cascade" }),
    // Natural FKs — all composite-FK'd below to share this row's organization_id (D-02).
    projectId: uuid("project_id").notNull(),
    unitId: uuid("unit_id").notNull(),
    paymentPlanId: uuid("payment_plan_id").notNull(),
    // snapshot — versioned calc envelope (D-13). Typed JSONB; validated by quoteInsertSchema.
    snapshot: jsonb("snapshot").$type<QuoteSnapshot>().notNull(),
    // pdf storage key — nullable; generated by Fase 3.
    pdfKey: text("pdf_key"),
    // lead_id — nullable pointer. NO `.references()` here; the FK to leads is added in 01-04
    // hand SQL to keep the module graph acyclic (leads ↔ quotes cycle-break).
    leadId: uuid("lead_id"),
  },
  (t) => [
    // PRIMARY composite FK (D-02): (project_id, organization_id) → projects.
    foreignKey({
      columns: [t.projectId, t.organizationId],
      foreignColumns: [projects.id, projects.organizationId],
    }).onDelete("cascade"),
    // SECONDARY composite FK (D-02): (unit_id, organization_id) → units.
    foreignKey({
      columns: [t.unitId, t.organizationId],
      foreignColumns: [units.id, units.organizationId],
    }).onDelete("cascade"),
    // SECONDARY composite FK (D-02): (payment_plan_id, organization_id) → payment_plans.
    foreignKey({
      columns: [t.paymentPlanId, t.organizationId],
      foreignColumns: [paymentPlans.id, paymentPlans.organizationId],
    }).onDelete("cascade"),
    // Parent UNIQUE so leads can composite-FK quotes on (id, organization_id) later.
    unique().on(t.id, t.organizationId),
    // Tenant policy ONLY (tenant-private — A5). `::text` cast; default-deny via missing_ok.
    // NO anon policy: quotes are never exposed to the public web.
    pgPolicy("quotes_tenant", {
      as: "permissive",
      for: "all",
      to: appAuthenticated,
      using: sql`${t.organizationId} = current_setting('app.current_organization_id', true)::text`,
      withCheck: sql`${t.organizationId} = current_setting('app.current_organization_id', true)::text`,
    }),
  ],
).enableRLS();

// Boundary validator (D-13): drizzle-zod infers z.any() for jsonb, so snapshot MUST be refined
// with the versioned-envelope schema. Callers import this to validate inserts.
export const quoteInsertSchema = createInsertSchema(quotes, {
  snapshot: quoteSnapshotSchema,
});
